version: '2'
services:
    revizor-app:
        image: revizor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://revizor-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=revizor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    revizor-mongodb:
        extends:
            file: mongodb.yml
            service: revizor-mongodb
