version: '2'
services:
    auditor-app:
        image: auditor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://auditor-postgresql:5432/auditor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    auditor-postgresql:
        extends:
            file: postgresql.yml
            service: auditor-postgresql
